/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseButton: typeof import('./components/Apps/BaseButton.vue')['default']
    CompBg: typeof import('./components/Apps/CompBg.vue')['default']
    Csr: typeof import('./components/Home/csr.vue')['default']
    Footer: typeof import('./components/Apps/Footer.vue')['default']
    LastestNews: typeof import('./components/Home/LastestNews.vue')['default']
    Loader: typeof import('./components/Apps/Loader.vue')['default']
    MainCarousel: typeof import('./components/Apps/MainCarousel.vue')['default']
    NavBar: typeof import('./components/Apps/NavBar.vue')['default']
    OurProject: typeof import('./components/Home/OurProject.vue')['default']
    Overlayloader: typeof import('./components/Apps/overlayloader.vue')['default']
    Partnerships: typeof import('./components/Home/Partnerships.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Services: typeof import('./components/Home/Services.vue')['default']
  }
}
